### ISSUE TITLE
Support PATH environment variable to look the provided executables up

### ISSUE THREAD

**Issue by v1nc3n4** [siouan/frontend-gradle-plugin#107]
As suggested by @ludik0 in #86, the plugin may accept a `null` `nodeInstallDirectory` property, respectively `yarnInstallDirectory`, when the distribution is provided on the system (`nodeDistributionProvided` property, resp. `yarnDistributionProvided` property, is `true`), and use the executable available through the `PATH` environment variable, if any.

Ideally, the plugin would resolve executable file path based on the following rules, ordered by descending priority:

1. Use the `nodeInstallDirectory` property if not `null`.
1. Use the `NODEJS_HOME`/`YARN_HOME` environment variable if it points to an existing directory, and if a relative executable path can be resolved from it.
1. Use the `PATH` environment variable.

**Comment by ludik0** [comment]
Thank you for putting it to the plan ! :)

Our usecase is that we use build-containers that have nodejs preinstalled but do not have an internet connection. Still I cannot rely on node being installed at the same place all the time so looking it up from the path would be perfect in this scenario.
