### ISSUE TITLE
Is that possible to make a build from two separate projects (server, client)? 

### ISSUE THREAD

**Issue by Leocete** [siouan/frontend-gradle-plugin#121]
Hi guys, I'm currently trying to build together two separate projects that are running on different ports:
**React - 3000**
**Spring Boot - 8080**

I can see an example of how it could be done with[ gradle-maven-plugin](https://dzone.com/articles/spring-boot-and-react-happily-ever-after) - here we are doing everything from the beginning step-by-step (installing node, yarn, all dependencies, building, copying resources, etc).

Is it possible to be done with **frontend-gradle-plugin**?
Cause in the examples I can see `build.gradle` file in each frontend folder, which is not the case when you are buiding front-end separately

This is my configuration: 
```
frontend {
    nodeVersion = '10.16.3'

    yarnEnabled = true
    yarnVersion = '1.21.1'
    yarnDistributionUrlRoot = 'https://github.com/yarnpkg/yarn/releases'

    installScript = 'install'

    packageJsonDirectory = '../client'
    proxyHost = 'localhost'
    proxyPort = 8080
}
```

How Gradle build knows where to put built files? How does it know when to execute it?

**Comment by v1nc3n4** [comment]
Hi @Leocete,

> Is that possible to make a build from two separate projects (server, client)?
Yes. This [example](https://github.com/siouan/frontend-gradle-plugin/tree/master/examples/multi-projects-war-application) in the repository is a good start point for such need.

Based on the example you gave with the frontend-maven-plugin, you shall probably just add the 2 following properties to your `build.gradle` file located in the `frontend` sub-project:

```groovy
assembleScript = 'run build'
checkScript = 'run test'
```

Let me know if that answers your question.
Regards,
Vincent

**Comment by v1nc3n4** [comment]
Hi,
I close the issue, since the discussion seems to be over. If you need any additional information, feel free to ask hereafter.
Thank you!
BR
