### ISSUE TITLE
Use system properties for HTTP proxy configuration

### ISSUE THREAD

**Issue by v1nc3n4** [siouan/frontend-gradle-plugin#136]
As suggested by @jorgheymans in issue #131, the plugin could use system properties to configure HTTP proxying of the download requests.

The default value for `proxyHost`, `proxyPort`, `proxyUsername`, `proxyPassword` would be taken respectively from `http.proxyHost`, `http.proxyPort`, `http.proxyUser`, `http.proxyPassword`.

**Comment by jorgheymans** [comment]
You should probably take into account the `https` variant also, and the `nonProxyHosts` for both cases as well to be complete e.g. https://medium.com/@petehouston/execute-gradle-behind-a-corporate-proxy-network-509260961813

**Comment by v1nc3n4** [comment]
Yes, Indeed, thank you.
