### ISSUE TITLE
Exit code from node.js is not passed to Gradle

### ISSUE THREAD

**Issue by landsman** [siouan/frontend-gradle-plugin#143]
Hi,

I have Gradle task for generating documentation for my project, using this plugin.

My command:  `antora generate antora-playbook.yml --to-dir build/docs/ --clean`

If this node.js script fail Gradle don't know that happend. So this build will pass which is problem on my CI.
Probably there is missing some exit code handling to the Gradle, right?

**Environment**
 
- OS: Ubuntu 20.04
- JDK: Open JDK 11
- Gradle: 4.4.1
- Frontend Gradle plugin: 4.0.1

Settings in `build.gradle.kts` file:
```
frontend {
    nodeVersion.set("14.15.0")
    nodeInstallDirectory.set(project.layout.projectDirectory.dir("build/nodejs"))
}

tasks.register<Exec>("beforeDocumentation") {
    commandLine = listOf("rsync", "-r", "build/generated-snippets/", "docs/modules/ROOT/partials/generated-snippets/")
}

tasks.register<RunNpmYarn>("documentation") {
    dependsOn(tasks.named("installNode"))
    dependsOn(tasks.named("installFrontend"))
    dependsOn(tasks.named("beforeDocumentation"))
    script.set("run doc")
}
```

My `package.json` file:
```
{
  "name": "api",
  "version": "1.0.0",
  "description": "api documentation",
  "main": "index.js",
  "scripts": {
    "doc": "antora generate antora-playbook.yml --to-dir build/docs/ --clean"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/trisbee/api.git"
  },
  "author": "Trisbee s.r.o.",
  "license": "ISC",
  "homepage": "https://github.com/trisbee/api#readme",
  "devDependencies": {
    "@antora/cli": "^2.3.4",
    "@antora/site-generator-default": "^2.3.4"
  }
}
```

**Example build**
```
> Task :beforeDocumentation
> Task :installNode
> Task :installYarn SKIPPED

> Task :installFrontend
added 239 packages from 201 contributors and audited 239 packages in 3.726s

14 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

> Task :documentation

> api@1.0.0 doc /codebuild/output/src144838887/src/github.com/trisbee/api
> antora generate antora-playbook.yml --to-dir build/docs/ --clean

asciidoctor: ERROR: detail.adoc: line 17: include target not found: partial$/generated-snippets/notification-backoffice-controller-test/notification-doesnt-exist/http-response.adoc

> Task :assembleFrontend SKIPPED
> Task :bootJar
> Task :inspectClassesForKotlinIC
> Task :jar SKIPPED
> Task :assemble

BUILD SUCCESSFUL in 4m 56s
```

**Comment by v1nc3n4** [comment]
Hello,

I was not able to reproduce this issue, neither on Linux nor on Windows. Given a sample project, in both cases, NPM reported a non-zero exit code which failed the build as expected.
Here's the configuration I used in a sample project:

- `package.json`:

```json
{
  ...
  "cacheDirectories": [
    "node_modules"
  ],
  "devDependencies": {
    "@antora/cli": "^2.3.4",
    "@antora/site-generator-default": "^2.3.4"
  },
  "scripts": {
    "commandWithNonZeroExitCode": "antora generate antora-playbook.yml --to-dir build/docs/ --clean",
    "commandWithZeroExitCode": "node -v"
  }
}
```

- `build.gradle`:

```kotlin
import org.siouan.frontendgradleplugin.infrastructure.gradle.RunNpmYarn

plugins {
    id("org.siouan.frontend-jdk11") version "4.0.1"
}
frontend {
    nodeVersion.set("14.15.1")
}
tasks.register<RunNpmYarn>("commandOk") {
    dependsOn(tasks.named("installFrontend"))
    script.set("run commandWithZeroExitCode")
}

tasks.register<RunNpmYarn>("commandKo") {
    dependsOn(tasks.named("installFrontend"))
    script.set("run commandWithNonZeroExitCode")
}
```

- Executing `gradlew commandOk` leads to `BUILD SUCCESSFUL`.
- Executing `gradlew commandKo` leads to `BUILD FAILED` due to the `/bin/sh` command returning an error code 1.

I wonder if the `antora` executable reports every error it encouters with a relevant exit code. I see 2 options:
- Can you execute directly from a command line `npm run doc; echo $?` and see what the exit code is.
- Could you check on your side this sample project and tell me what's going on, so as I can better understand what's happening?

Thank you in advance for your help!
Best regards

**Comment by v1nc3n4** [comment]
Hi @landsman 

> **Environment**
>    OS: Ubuntu 20.04
>    JDK: Open JDK 11
>    Gradle: 4.4.1
>    Frontend Gradle plugin: 4.0.1

I have just noticed once thing given your environment: the plugin is supported from Gradle 5.1 (see the [Getting started](https://siouan.github.io/frontend-gradle-plugin/getting-started) section in the documentation.
Consequently, there's no guarantee the plugin works as expected with Gradle 4.4.1, and you have no other choice than upgrading Gradle to use the plugin.

Let me know your feedback before I close the issue.
Thank you.
BR

**Comment by landsman** [comment]
Thank you very much! 
I will let you know after Gradle upgrade.

**Comment by v1nc3n4** [comment]
Hi,
Do you have any news about this issue? Is it still present, and if yes, are you able to provide a sample project so as I can reproduce it on my workstation?
Thanks for your help!
BR

**Comment by landsman** [comment]
Actually problem was in Antora project where another dependency - Asciidoctor do not passing exit code correctly.
More here: https://gitlab.com/antora/antora/-/issues/402.

Sorry for disturbing here.

**Comment by v1nc3n4** [comment]
Hi @landsman,
Thank you for this feedback. Have a good day!
