### ISSUE TITLE
[Help needed] UnsupportedPlatformException when building on arm/v7

### ISSUE THREAD

**Issue by Griefed** [siouan/frontend-gradle-plugin#165]
Hey there,

I'm trying to make use of your frontend plugin on amd64, arm/v7 and arm64/arm/v8, but unfortunately it fails when a CI job runs on arm/v7 when building a multiarch Docker image.
Is there something I can do to resolve this issue from my end?

Any help at all would be much appreciated. 🙂

The error I get:

> 249.5 > Task :installNode FAILED
 249.7 
 249.7 FAILURE: Build failed with an exception.
 249.7 
 249.7 * What went wrong:
 249.7 Execution failed for task ':installNode'.
 249.7 > org.siouan.frontendgradleplugin.domain.exception.UnsupportedPlatformException: This platform is not supported yet: Platform {jvmArch=arm, osName=Linux, environment=Environment {nodeInstallDirectory=null, yarnInstallDirectory=null}}

**Environment**
 
- OS: Alpine Linux
- JDK: OpenJDK-8
- Gradle: Gradle 7.1.1
- Frontend Gradle plugin: frontend-jdk8 version 5.2.0
- Settings in `build.gradle[.kts]` file:
```groovy
frontend {
    packageJsonDirectory = file("${projectDir}/frontend")

    nodeVersion = '16.1.0'
    nodeInstallDirectory = file("${projectDir}/frontend/node")

    yarnEnabled = false
    yarnVersion = "1.22.10"
    yarnInstallDirectory = file("${projectDir}/frontend/yarn")

    cleanScript = 'run clean'
    assembleScript = 'run build'
}
```

**Attachments**
The Dockerfile in question: https://git.griefed.de/Griefed/ServerPackCreator/-/blob/webservice/Dockerfile.webservice
The full buidl.gradle file: https://git.griefed.de/Griefed/ServerPackCreator/-/blob/webservice/build.gradle
Full log of the build process: https://git.griefed.de/Griefed/ServerPackCreator/-/jobs/1566#L460 (See line 460 where the error occured.)

Thank you very much for this awesome plugin. Without it, I would have a tough time trying to build my project 😅

**Comment by v1nc3n4** [comment]
Hi @Griefed,

Thank you very much for reporting this issue.

### Automatic resolution

As the error suggests it, the plugin is not able to resolve _automatically_ the relevant distribution of Node.js for the underlying platform (Linux / ARMv7). Let's plan this improvement for the next release, and improve the error message to guide the end-user in the resolution of this problem.

### Workaround

The automatic resolution simplifies configuration in the build script, and avoids implementing logic to switch from a given distribution to another, depending on the build/CI platform. However, and particularly with this error, using custom logic in the build script is the a workaround I can suggest to you until the next release containing the automatic resolution on ARMv7 architectures is delivered.

Consequently, you should customize the [nodeDistributionUrlPathPattern](https://siouan.github.io/frontend-gradle-plugin/configuration#nodeDistributionUrlPathPattern) property:
```groovy
frontend {
    // On your CI platform only / do not include this line on non-ARMv7 platforms
    nodeDistributionUrlPathPattern = 'vVERSION/node-vVERSION-armv7l.TYPE'
}
```

Let me know if it works with this tweak on your CI platform (I am not able to test it on my own, since I do not have an ARMv7 platform by my side).
BR

**Comment by Griefed** [comment]
Thank you very much for your reply. Don't stress yourself with a release, take your time. I'd rather you take your time and get a good release out there, than doing a Cyberpunk and releasing too early. 🙂

We are getting somewhere. The build still fails, but this time I get the error message 

> org.siouan.frontendgradleplugin.domain.exception.ResourceDownloadException: Unexpected HTTP response: HTTP/1.1 404 Not Found

```java
frontend {
    packageJsonDirectory = file("${projectDir}/frontend")

    nodeVersion = '16.1.0'
    nodeInstallDirectory = file("${projectDir}/frontend/node")

    yarnEnabled = false
    yarnVersion = "1.22.10"
    yarnInstallDirectory = file("${projectDir}/frontend/yarn")

    cleanScript = 'run clean'
    assembleScript = 'run build'

    // Print the architecture we are running on.
    System.out.println(String.format("I am running on: %s", System.getProperty("os.arch")))

    // If we are running on arm, specify Node path pattern so arm-builds succeed.
    if (System.getProperty("os.arch").equals("arm")) {
        nodeDistributionUrlPathPattern = 'vVERSION/node-vVERSION-armv7l.TYPE'
    }
}
```

In order to use the frontend plugin with multiarch Docker images, I set `nodeDistributionUrlPathPattern` depending on the os.arch system property. When the arm-build starts, the logs correctly state 

> #8 197.6 I am running on: arm

So I was hoping it would work, but now it 404s. 😅 

Cheers,
Griefed

**Comment by v1nc3n4** [comment]
Great,
FYI, there's no complexity about improving and releasing an automatic resolution for ARMv7. I just need to be sure what the target Node.js distribution is, so as it can be mapped with this architecture in the plugin 😄.

Before the 404 error, there you should be a log line like `Downloading resource at...`. Can you provide the whole log line, or report what URL the plugin attempts to download a resource from?

Thank you!

**Comment by Griefed** [comment]
I was able to reproduce this issue on a Raspberry Pi with the same result. Here is the log output:

> [installNode] Removing install directory '/home/pi/Downloads/ServerPackCreator/frontend/node'
> [installNode] Downloading distribution at 'https://nodejs.org/dist/v16.1.0/node-v16.1.0-armv7l.tar.gz'
> [installNode] Downloading resource at 'https://nodejs.org/dist/v16.1.0/node-v16.1.0-armv7l.tar.gz' (proxy: DIRECT)
> :installNode (Thread[Execution worker for ':',5,main]) completed. Took 0.208 secs.
>
> FAILURE: Build failed with an exception.
>
> * What went wrong:
> Execution failed for task ':installNode'.
> org.siouan.frontendgradleplugin.domain.exception.ResourceDownloadException: Unexpected HTTP response: HTTP/1.1 404 > > Not Found

Ooooh I see, it wants to fetch `node-v16.1.0-armv7l.tar.gz` but NodeJs provides `node-v16.1.0-linux-armv7l.tar.gz ` for download.

**Comment by v1nc3n4** [comment]
Sorry, my fault, I did not copy the exact URL in my previous post. Let me know the result with the right URL 😃.

**Comment by Griefed** [comment]
I've expanded the frontend configuration to
```java
    // Print the architecture we are running on.
    System.out.println(String.format("I am running on: %s", System.getProperty("os.arch")))

    // If we are running on arm, specify Node path pattern so arm-builds succeed.
    if (System.getProperty("os.arch").equals("arm")) {
        nodeDistributionUrlPathPattern = 'vVERSION/node-vVERSION-linux-armv7l.TYPE'
    } else if (System.getProperty("os.arch").equals("aarch64")) {
        nodeDistributionUrlPathPattern = 'vVERSION/node-vVERSION-linux-arm64.TYPE'
    }
```

The build still fails, but not because of NodeJS. This time, it's because of a missing library `libatomic1` which I will figure out eventually.

Thank you very much for your help. I will go ahead and close this issue.

Keep up the good work! Stay safe and stay awesome.

Cheers,
Griefed

**Comment by v1nc3n4** [comment]
Very happy to read these good news!

I just keep the issue opened, because the automatic resolution shall deal with ARMv7 architectures, and an improvement is now pending 😃.

Thank you for your support!

**Comment by Griefed** [comment]
Thank you for the new release.
Works like a charm. Thank you very much! 👍

Stay safe and stay awesome.
Cheers,
Griefed
