### ISSUE TITLE
Ability to create own Gradle task that calls Yarn/NPM task?

### ISSUE THREAD

**Issue by trohr** [siouan/frontend-gradle-plugin#178]
Hi,

Is it possible to easily create own Gradle task that calls some task defined in `package.json`?

We have separate yarn task to generate some javascript sources from openapi specification (named `generate-sources-from-openapi`) and we would like to integrate it into the build process via gradle.

We have found a workaround by configuring `assembleScript = 'generate-sources-from-openapi && yarn build'. But this might have its downsides (e.g. I am not sure, but doesn't that 'yarn' in the command call global yarn on the machine, rather than the one your plugin manages?)

How I think we would like to define a new task: `build.gradle`:
```groovy
frontend {
    // Provide the expected plugin settings.
}

// see https://github.com/siouan/frontend-gradle-plugin/blob/master/src/main/java/org/siouan/frontendgradleplugin/infrastructure/gradle/AbstractRunCommandTask.java
tasks.register('generateSourcesFromOpenapi', AbstractRunCommandTask) {
	group 'Frontend'
	description "Generates JS sources from OpenApi specification"
	script = 'run generate-sources-from-openapi'
}
```

In my mind the task should be configured with all of the common conifguration of the plugin. 

Is this correct usage? Can you please point me to the right direction?

Thank you.

Sincerely yours,
Tomas Rohrbacher

**Comment by v1nc3n4** [comment]
Hello Tomas,

Thank you for your question and for using the plugin!
I think you should take a look at [this page](https://siouan.github.io/frontend-gradle-plugin/node-npm-npx-yarn-tasks) in the documentation where "task types" are introduced in details: `RunNode`, `RunNpm`, `RunNpx`, `RunYarn`. Task types are provided exactly for your use case, with a concrete example to show how to register a custom task to execute a script defined in the `package.json` file.

Let me know if it helps!
BR

**Comment by trohr** [comment]
> Hello Tomas,
> 
> Thank you for your question and for using the plugin! I think you should take a look at [this page](https://siouan.github.io/frontend-gradle-plugin/node-npm-npx-yarn-tasks) in the documentation where "task types" are introduced in details: `RunNode`, `RunNpm`, `RunNpx`, `RunYarn`. Task types are provided exactly for your use case, with a concrete example to show how to register a custom task to execute a script defined in the `package.json` file.
> 
> Let me know if it helps! BR

Oh, thank you very much, your answer helped.

```groovy
import org.siouan.frontendgradleplugin.infrastructure.gradle.RunYarn
tasks.register('e2e', RunYarn) {
    // dependsOn tasks.named('installNode')
    // dependsOn tasks.named('installFrontend')
    script = 'run e2e'
}
```
