### ISSUE TITLE
Support of package managers through corepack

### ISSUE THREAD

**Issue by v1nc3n4** [siouan/frontend-gradle-plugin#183]
Using Node.js [`corepack`](https://nodejs.org/dist/latest/docs/api/corepack.html) utility may simplify the process executed between task `installNode` and task `installFrontend`, incremental build should be possible, and supporting additional package managers may be easier (PNPM):

- Task `installGlobalYarn` would be replaced by task `preparePackageManager`:
  - New inputs: Node.js install directory
  - New outputs: `npm[.cmd]` and `npx[.cmd]` proxy executables when NPM is the package manager, `yarn[.cmd]` and `yarnpkg[.cmd]` when Yarn is the package manager.
- Task `enableYarnBerry` would be removed.
- Task `installYarn` would be now skippable:
  - New outputs: `${projectDir}/.yarn/releases/yarn-<VERSION>.cjs`

These orientations must be confirmed however.

**Comment by v1nc3n4** [comment]
Manual tests suggest the following task chain before running a `npm`/`pnpm`/`yarn` command:
1. `installNode`: downloads and install the relevant Node.js distribution.
2. `installPackageManager`: parses the `packageManager` property in the `package.json` file, and runs `corepack enable <package-manager-name>`.

Development tasks:

- [X] Replace directory output of task `installNode` with a simple path output (changes in the Node.js install directory will not trigger a new download and installation).
- [ ] IN PROGRESS - Implement task `installPackageManager`:
  - Inputs: `packageJsonFile = packageJsonDirectory + '/package.json'`.
  - Outputs: `packageManagerProxyFile = nodeInstallDirectory/[bin/]<package-manager>[.cmd]`.
- [ ] Remove tasks `installGlobalYarn`, `enableYarnBerry`, `installYarn`.
- [ ] Remove all `yarn*` properties.
- [ ] Update documentation and examples.

**Comment by steve-todorov** [comment]
Hey, 

Incremental `npm` builds would be pretty awesome and time saving, specially with Angular builds!
I was wondering if there is any ETA on this ticket? (no exact dates of course, but rather a vague approximation would be enough)
By the looks of it you have done most of the work, is that right?

Right now I'm occupied with work, but since this would significantly improve my overall development as well as build process I could give a hand with coding or QA if necessary. If there are clearly defined tasks and published code - I would be more than happy to contribute and maybe get this released within November?

**Comment by v1nc3n4** [comment]
Hi @steve-todorov

First of all, I want to thank you for your message and your proposal.
This feature will be available in release 7.0.0. Unfortunately, I thought I could publish this release last summer, but I struggled to find enough time for that. However now, the feature is almost done as you noticed it (there's still an important update of the documentation remaining).  There's also a refactoring pending to restore a clean code layout, and some minor issues have to be fixed. A pessimistic ETA would be the end of the year. There may be some good news by the end of november however :wink:.

Thank you for your support!

BR

**Comment by steve-todorov** [comment]
That's awesome news! I saw your PR and it looks like you have changed just a few files :sweat_smile: :smile: 
Looking forward to checking this out when it's ready.

**Comment by v1nc3n4** [comment]
Hi all,
Actually, releasing this feature is blocked due to an issue with NPM support and "recent" releases of Node.js (16.17+, 18, maybe some 14?).
For reference: https://github.com/nodejs/corepack/issues/178

I'd like to get a feedback on this issue from Node community before deciding to release or not the feature. Support of NPM with Corepack is a little ambiguous and a rework may be necessary depending on how the issue is dealt with by the community.
BR
