### ISSUE TITLE
Support node on alpine linux

### ISSUE THREAD

**Issue by GandalfIX** [siouan/frontend-gradle-plugin#185]
Hi,

**Description**

I would like to use an alpine docker container to build my Java and JS/TS application.

Whenever I try to execute the build from within the alpine container it fails with:
```
[installNode] Removing install directory '/workspace/frontend/node'
[installNode] Downloading distribution at 'https://nodejs.org/dist/v16.16.0/node-v16.16.0-linux-x64.tar.gz'
[installNode] Downloading resource at 'https://nodejs.org/dist/v16.16.0/node-v16.16.0-linux-x64.tar.gz' (proxy: DIRECT)
[installNode] Downloading resource at 'https://nodejs.org/dist/v16.16.0/SHASUMS256.txt' (proxy: DIRECT)
[installNode] Verifying distribution integrity
[installNode] Exploding distribution into '/workspace/frontend/build/tmp/installNode/extract'
[installNode] Moving distribution into '/workspace/frontend/node'
[installNode] Removing explode directory '/workspace/frontend/build/tmp/installNode/extract'
[installNode] Removing distribution file '/workspace/frontend/build/tmp/installNode/node-v16.16.0-linux-x64.tar.gz'
[installNode] Distribution installed in '/workspace/frontend/node'

....

[installFrontend] Install directory resolved from extension: /workspace/frontend/node
[installFrontend] Executable '/workspace/frontend/node/bin/node' resolved from install directory
[installFrontend] Install directory resolved from extension: /workspace/frontend/node
[installFrontend] Executable '/workspace/frontend/node/bin/npm' resolved from install directory
[installFrontend] Running '/bin/sh' with arguments: [-c], ["/workspace/frontend/node/bin/npm" install]
env: can't execute 'node': No such file or directory

```
while it works normally on Ubuntu or Windows.

While analyzing this issue I stumbled across https://github.com/siouan/frontend-gradle-plugin/issues/179 which pointed in the correct direction.

From other sources it became obvious that you would need to download a different (musl compatible) version of node for this to work.
These version are provided by node under eg. https://unofficial-builds.nodejs.org/download/release/v16.16.0/node-v16.16.0-linux-x64-musl.tar.xz 

When configuring the plugin using the following values it is able to download the files and execute node as expected
```
nodeDistributionUrlRoot = 'https://unofficial-builds.nodejs.org/download/release/'
nodeDistributionUrlPathPattern = 'vVERSION/node-vVERSION-ARCH-musl.TYPE'
```
Therefore it would be great if you could detect alpine correctly and adapt the distribution-Information accordingly.

Thanks :-)

**Target environment**
 
- OS: alpine linux
- JDK: 17 (via eclipse-temurin:17-jdk-alpine docker image)
- Gradle: 7.5

Settings in `build.gradle`

```groovy
frontend {
    nodeVersion = '16.16.0'
    installScript = 'install'
    assembleScript = 'run build'
    checkScript = 'run testCI'
    verboseModeEnabled = true
}
```

**Comment by v1nc3n4** [comment]
Hi @GandalfIX,

Thank you for using this plugin.

It's difficult to know what's happening without detailed information about the underlying platform, and your Gradle build. There's a template to report an issue, and it is very important to provide the requested data in this template. Please, take a look at this template, and provide detailed information so as I can help you.

Apart from that:

> \> Task :frontend:npmSetup FAILED
> env: can't execute 'node': No such file or directory

There's no built-in task named `npmSetup` in the plugin. I don't know what plugins you are using and what task(s) you are running with Gradle inside the container.

I suggest you:
- enable the plugin to be verbose (`verboseModeEnabled` property),
- run `gradle[w] installFrontend --rerun-tasks` in the container,
- provide console ouput in the issue.

That's the starting point to know whether Node.js is correctly downloaded, and if the plugin is able to run `node` executable as expected.

Let me know detailed information as requested so as I can help!
BR

**Comment by GandalfIX** [comment]
Hey @v1nc3n4,
Sorry for the inconvenience.
I have updated the initial comment with the requested information, hope that is more helpful now.

**Comment by v1nc3n4** [comment]
Hi @GandalfIX,

I dug deeper into the issue you are facing. Technically speaking, I guess detecting if the O/S is Alpine should be possible.

The problem with dealing with unsupported platforms is perfectly introduced [here](https://unofficial-builds.nodejs.org/).
Here are also some references that explain why Alpine is not officially supported yet: [\[1\]](https://github.com/nodejs/node/blob/main/BUILDING.md#supported-platforms) [\[2\]](https://github.com/nodejs/build/issues/1140)

I don't think it is a good idea to provide built-in support in the plugin for "unofficial" releases of Node.js, since these are releases that may not have passed tests. Of course, I assume a lot of people would be interested with an Alpine-compatible build, but to me, the need should be raised to Node.js team so as the platform receives a verified and official build first.

> When configuring the plugin using the following values it is able to download the files and execute node as expected
> > nodeDistributionUrlRoot = 'https://unofficial-builds.nodejs.org/download/release/'
> > nodeDistributionUrlPathPattern = 'vVERSION/node-vVERSION-ARCH-musl.TYPE'

Yes, this is what I would recommend to do until Node.is team provides an official release for Alpine.

BR

**Comment by GandalfIX** [comment]
Hey @v1nc3n4 ,

Thanks for your analysis. I understand that you don't want to support "unofficial" releases. Then I'll go with my workaround.

For reference:
With the definition below you can use
`./gradlew -PrunOnAlpine`
to create a build that is working on alpine-Linux using the unofficial builds of node.js

```
def nodeDistributionUrlRootOverride = null
def nodeDistributionUrlPathPatternOverride = null
if (project.hasProperty("runOnAlpine")) {
    nodeDistributionUrlRootOverride = 'https://unofficial-builds.nodejs.org/download/release/'
    nodeDistributionUrlPathPatternOverride = 'vVERSION/node-vVERSION-ARCH-musl.TYPE'
}

frontend {
    nodeVersion = '16.16.0'
    nodeDistributionUrlRoot = nodeDistributionUrlRootOverride
    nodeDistributionUrlPathPattern = nodeDistributionUrlPathPatternOverride
}
```
