### ISSUE TITLE
Ability to set Corepack version

### ISSUE THREAD

**Issue by v1nc3n4** [siouan/frontend-gradle-plugin#212]
Node.js/Corepack bundles provided in Node.js distributions frequently suffer from bugs that avoid installing package manager or dependencies, and lead to failures when task `installFrontend` is executed. As a end-user, it is difficult to identify the causes of such failures, and how to work around them quickly ([this issue](https://github.com/siouan/frontend-gradle-plugin/issues/210) for example).

The plugin could provide a property allowing the end-user to replace the Corepack release bundled by default in the Node.js distribution with another one (typically the latest). A new task `installCorepack` could use this property to update Corepack release.

#### DSL

```kotlin
frontend {
    // may be null (by default), or "latest", or a concrete version number
    corepackVersion.set("latest")
}
```

#### Task `installCorepack`

- Dependency graph: `installPackageManager` -> `installCorepack` -> `installNode`
- Skippable: if `corepackVersion` is `null`
- Inputs: `Property<String>` `corepackVersion`
- Outputs: `DirectoryProperty` `<nodeInstallDirectory>/node_modules/corepack`

**Comment by MBelniak** [comment]
Yes! I'd love to use COREPACK_NPM_REGISTRY, but it's not there in the currently used version of corepack yet. I wish I could set the version of corepack to something newer.

**Comment by v1nc3n4** [comment]
Hi @MBelniak,

Thank you for using the plugin and your feedback.
I'm not sure I can deal with this new feature before March 2024. You may look at [this comment](https://github.com/siouan/frontend-gradle-plugin/issues/210#issuecomment-1740903000) for 
a workaround until the feature is released.

BR

**Comment by MBelniak** [comment]
I switched to gradle-node-plugin instead :p

**Comment by v1nc3n4** [comment]
Great! I wish you can choose the version of Corepack with a simple configuration option if this feature exists with this plugin. Otherwise, feel free to get in touch with next releases here.

BR
