### ISSUE TITLE
Invalid JSON file

### ISSUE THREAD

**Issue by DaiYuANg** [siouan/frontend-gradle-plugin#216]
> Before creating an issue, please:
> - Check you are using the latest plugin release.
> - Check the issue was not reported yet.

---

Hi,

**Description**

What I am trying to do: gradle build with vite
Expected results: task execute sucess
Actual results: Invalid JSON file: xxx/xxx/package.json

**Environment**
 
- OS: Mac OS X
- JDK: GraalVM JDK 21 64 bits
- Gradle: Gradle 8.5
- Frontend Gradle plugin: 8.0.0 JDK 17

Settings in `build.gradle[.kts]` file:
```kotlin
plugins{
    id("org.siouan.frontend-jdk17") version "8.0.0"
}

frontend{
    nodeVersion.set("20.9.0")
}
```

**Attachments**
```json
{
  "name": "frontend web",
  "private": true,
  "version": "0.0.0",
  "type": "module",
  "scripts": {
    "dev": "vite",
    "build": "tsc && vite build",
    "lint": "eslint . --ext ts,tsx --report-unused-disable-directives --max-warnings 0",
    "preview": "vite preview"
  },
  "dependencies": {
    "react": "^18.2.0",
    "react-dom": "^18.2.0"
  },
  "devDependencies": {
    "@types/react": "^18.2.37",
    "@types/react-dom": "^18.2.15",
    "@typescript-eslint/eslint-plugin": "^6.10.0",
    "@typescript-eslint/parser": "^6.10.0",
    "@vitejs/plugin-react": "^4.2.0",
    "eslint": "^8.53.0",
    "eslint-plugin-react-hooks": "^4.6.0",
    "eslint-plugin-react-refresh": "^0.4.4",
    "typescript": "^5.2.2",
    "vite": "^5.0.0"
  }
}
```
There is new generate from pnpm create vite when I run any task from this plugin it will throw resolvePackageManager :Invalid JSON file

**Comment by v1nc3n4** [comment]
Hi @DaiYuANg,

As the error message states it, the `package.json` file is invalid regarding task `resolvePackageManger`. Indeed, mandatory property `packageManager` is missing. Official documentation of this task [here](https://siouan.github.io/frontend-gradle-plugin/node-corepack-npm-pnpm-yarn-tasks#resolvePackageManager) should help you fix this file so as the plugin can resolve the package manager used by the project.

Let me know if this helps.
BR
