### ISSUE TITLE
Allow to specify NODE_OPTIONS

### ISSUE THREAD

**Issue by mgiorgino-iobeya** [siouan/frontend-gradle-plugin#220]
Hi,

**Description**

It would be nice if we could give options to the node process, like for example:

`NODE_OPTIONS=--max_old_space_size=50`

I didn't found a way to do it, but maybe there already is ?

**Target environment**
 
- OS: Ubuntu 22.04
- JDK: OpenJDK 64-Bit Server VM Corretto-17.0.8.7.1
- Gradle: Gradle 8.4

**Comment by v1nc3n4** [comment]
Hi @mgiorgino-iobeya,

Thank you for using the plugin and your question.
Apart from setting such environment variable in the system, which would be applicable to all processes, I don't see a way to do that for a Node.js-based task provided by the plugin for the moment. I understand it can be problematic on some platforms, like CI/CD.

Can you confirm this is the use case you are dealing with?

It should be possible to implement this feature in the next release [8.1.0](https://github.com/siouan/frontend-gradle-plugin/milestone/26) coming soon.
If you have another use case in mind, feel free to share this one here so as I can be sure the designed feature will meet your expectations.

BR

**Comment by mgiorgino-iobeya** [comment]
Hi @v1nc3n4, sorry I didn't answered earlier, but it was indeed in the context of a CI/CD environment. I think what was implemented will meet our expectations.

Thank you very much !
