### ISSUE TITLE
8.1.0 has undocumented breaking change(s)

### ISSUE THREAD

**Issue by bric3** [siouan/frontend-gradle-plugin#237]
The Gradle configuration cache fixes appears to have changed the `RunYarn` constructor.

https://github.com/siouan/frontend-gradle-plugin/commit/89c475db70a74be5a5c6af298bd500f6042a2907?diff=unified&w=0#diff-cd8d9534ecdea881b46c09dd8284805d46c51cbbb93332c15001e6566a5bff71L31-R31

There maybe other changes like this.

Note I'm not challenging the change, just stating this should be mentioned in the release changes ;)

**Comment by v1nc3n4** [comment]
Hi @bric3,

Glad to read you again, thank you for your remark.
Actually, I don't see why this change in the constructor of the `RunYarn` class should be considered as a breaking change. On the end-user point of view, I mean for someone who writes build scripts, there's nothing to change when upgrading from release 8.0.0 to release 8.1.0. I don't remember of a modification in the [official documentation](https://siouan.github.io/frontend-gradle-plugin/node-corepack-npm-pnpm-yarn-tasks/#RunYarn) for the usage of this task type. End-users still write `tasks.register<RunYarn>("myCustomTask") { ... }` (Kotlin) and the constructor is internally called by Gradle whatever its signature is.

What do you do that upgrading to release 8.1.0 may have broken?

Of course, if you are modifying/extending the plugin code for your own purpose, that's a different story.

If I am missing something, please let me know!
BR

**Comment by bric3** [comment]
Indeed, I do have tasks like this `register<RunYarn>("runYarnStart") { ... }`, but I wanted to be able to execute any tasks from gradle on the command line, and the `script` property is protected, so I created a subtask from `RunYarn` (8.0.0 code) :

```kotlin
tasks.register<YarnProxy>("yarn") {
    group = "frontend"
    description = "Run yarn script, e.g. for 'yarn add -D eslint', you can use './gradlew yarn --command=\"add -D eslint\"'"
}

open class YarnProxy @Inject constructor(
    projectLayout: ProjectLayout,
    objectFactory: ObjectFactory,
    execOperations: ExecOperations
) : RunYarn(
    projectLayout,
    objectFactory,
    execOperations
) {
    @Suppress("UnstableApiUsage")
    @set:Option(option = "command", description = "The command to pass to yarn")
    @get:Input
    var script: String = ""
        set(value) {
            super.getScript().set(value)
        }

    init {
        super.getScript().set(script)
    }
}
```

And this of course requires to extends this class. In 8.1.0 the `projectLayout: ProjectLayout` is gone.

**Comment by v1nc3n4** [comment]
Great!
I think this feature (setting the `script` property for task types from the command line) could be added to the plugin and a new release delivered quickly. This will avoid the need to override the plugin classes.
Is it good for you?

**Comment by bric3** [comment]
Yes, maybe this could be added on all `Run*` tasks. For reference here's what my proxy looks like in 8.1.0. I believe that annotating the parent class with this `@set:Option(option = "command", description = "The command to pass to yarn")` would be enough.

```kotlin
open class YarnProxy @Inject constructor(
    objectFactory: ObjectFactory,
    execOperations: ExecOperations
) : RunYarn(
    objectFactory,
    execOperations
) {
    @set:Option(option = "command", description = "The command to pass to yarn")
    @get:Input
    var yarnArgs: String = ""
        set(value) {
            super.script = value
        }

    init {
        super.script = yarnArgs
    }
}
```

**Comment by v1nc3n4** [comment]
Hi,

I'm closing the issue because there's no breaking change in release 8.1.0, as explained above. But there's an implicit feature request, and this has been described in issue #238.

BR

**Comment by v1nc3n4** [comment]
Hi,

FYI, [release 9.0.0](https://github.com/siouan/frontend-gradle-plugin/releases/tag/v9.0.0) provides new tasks to execute instant commands from Gradle command line, and allows custom tasks based on task types to pass executable arguments as a command line option.

BR
