### ISSUE TITLE
Resolve Windows with ARM64 architecture correctly

### ISSUE THREAD

**Issue by t-h-e** [siouan/frontend-gradle-plugin#249]
Hi,

currently windows systems with only be resolved to either 64bit or 32bit.

See
- https://github.com/siouan/frontend-gradle-plugin/blob/main/plugin/src/main/java/org/siouan/frontendgradleplugin/domain/installer/ResolveNodeDistributionArchitectureId.java#L39-L47
- https://github.com/siouan/frontend-gradle-plugin/blob/main/plugin/src/main/java/org/siouan/frontendgradleplugin/domain/installer/ResolveNodeDistributionArchitectureId.java#L59

While Windows on ARM supports emulating x64, the build times are significantly solwer with x64. frontend-gradle-plugin should resolve Windows on ARM to `win-arm64` to download the correct node build.

The downside is that official node builds for win-arm64 are only available starting version >=19
For lower version, one can still overwrite [nodeDistributionUrlPathPattern](https://siouan.github.io/frontend-gradle-plugin/configuration/#nodeDistributionUrlPathPattern)

**Comment by v1nc3n4** [comment]
Hi @t-h-e,

Thank you for using this plugin and for this important request.
I just want to be sure we implement things correctly. Please, can you provide the result of this command on your Windows ARM workstation?

> java -XshowSettings:properties -version

Remove/hide any sensitive data (personal information, ...) before answering to this question.
Thanks in advance for your help!
BR

**Comment by t-h-e** [comment]
```
PS C:\Users\$user> java -XshowSettings:properties -version
Property settings:
    ...
    os.arch = aarch64
    os.name = Windows 11
    os.version = 10.0
    ...

openjdk version "17.0.12" 2024-07-16 LTS
OpenJDK Runtime Environment Microsoft-9889599 (build 17.0.12+7-LTS)
OpenJDK 64-Bit Server VM Microsoft-9889599 (build 17.0.12+7-LTS, mixed mode, sharing)
```
