### ISSUE TITLE
NoSuchMethodError: java/nio/ByteBuffer.flip()Ljava/nio/ByteBuffer

### ISSUE THREAD

**Issue by mike-howell** [Siouan/frontend-gradle-plugin#55]
Hi,

Java 9 changed the interface to ByteBuffer.flip() from returning Buffer to ByteBuffer. In the FileHasherImpl.has method calls the flip method on a Java 8 it will throw a NoSuchMethodError exception.

I googled the error and found this: [https://github.com/plasma-umass/doppio/issues/497](at the doppio project)

My stacktrace:

`Caused by: java.lang.NoSuchMethodError: java/nio/ByteBuffer.flip()Ljava/nio/ByteBuffer; (loaded from C:\Program Files\AdoptOpenJDK\jdk-8.0.212.03-openj9\jre\lib\rt.jar by <Bootstrap Loader>) called from class org.siouan.frontendgradleplugin.core.FileHasherImpl (loa
ded from file:/C:/Users/HowellM/.gradle/caches/modules-2/files-2.1/org.siouan/frontend-gradle-plugin/1.2.0/46a6a486eabfd2643fb05e85f4aba508da14cfc1/frontend-gradle-plugin-1.2.0.jar by VisitableURLClassLoader(ClassLoaderScopeIdentifier.Id{root:C:\Users\HowellM\IdeaP
rojects\dispatch-workflow\buildSrc:root-project(export)})).
        at org.siouan.frontendgradleplugin.core.FileHasherImpl.hash(FileHasherImpl.java:38)
        at org.siouan.frontendgradleplugin.core.NodeDistributionValidator.validate(NodeDistributionValidator.java:74)
        at org.siouan.frontendgradleplugin.core.DistributionInstaller.install(DistributionInstaller.java:61)
        at org.siouan.frontendgradleplugin.tasks.NodeInstallTask.execute(NodeInstallTask.java:83)
`

**To Reproduce**
I just followed the README here at the project in a very vanilla Spring Boot 2.1.5-RELEASE rest api application with a default generated vue cli project added to a sub folder and then I ran gradlew build and got the error.

**Environment:**
 - OS: Windows 10 Enterprise
 - JDK: AdoptOpenJDK 1.8.0_212-b03 / Eclipse OpenJ9 openj9-0.14.0
 - Gradle: 5.2.1
 - Frontend Gradle plugin: 1.2.0

**Comment by vboriesazeau** [comment]
Hi Michael,

Thank you for this feedback. I could reproduce the problem. The fix will be available quickly.

Regards,
Vincent
