### ISSUE TITLE
Provide option to customize the location of the root-folder for frontend code.

### ISSUE THREAD

**Issue by davidkron** [Siouan/frontend-gradle-plugin#57]
Since each project is different and often the structure must follow some company policy, I think it would be useful to have an option to specifiy the root-folder (location of package.json) where the frontend code is located.

The frontend-maven-plugin also supports this option and usually tutorials put the frontend code in **src/main/frontend**. I wouldn't go as far as to set this new option to a specific value, but as an optional possibility to customize.

**Comment by vboriesazeau** [comment]
Hi @davidkron,
Thank you for your message. I agree customizing the location of the `package.json` file would be useful. Let's plan it for the next release. The location of the frontend code is not constrained by the plugin however. It can be placed wherever the developer wants (e.g. `main/src/frontend`, `js/app`...).
Regards
Vincent
