### ISSUE TITLE
Cannot configure plugin with Kotlin DSL

### ISSUE THREAD

**Issue by byxor** [Siouan/frontend-gradle-plugin#59]
✅ Hi. I'm trying to **configure this plugin using Kotlin** (as opposed to groovy):

```
// build.gradle.kts

plugins {
    // ...
    id("org.siouan.frontend") version "1.2.1"
}

// ...

frontend {
    nodeVersion = "6.11.3"
    cleanScript = "run clean"
    assembleScript = "run assemble"
    checkScript = "run check"
}
```

:warning: But I'm getting the following **compilation errors** for each line in the `frontend` block:

```
Val cannot be reassigned
Type mismatch: inferred type is String but Property<String!>! was expected
```

<img width="327" alt="image" src="https://user-images.githubusercontent.com/14977217/64857814-8a0cc880-d61d-11e9-9270-17a6357f3b03.png">

---

🤔💭 I **expect the build script to compile** and work as though I had written the following groovy code in my build script:

```groovy
// build.gradle (example)

plugins {
    // ...
    id 'org.siouan.frontend' version '1.2.1'
}

// ...

frontend {
    nodeVersion = '6.11.3'
    cleanScript = 'run clean'
    assembleScript = 'run assemble'
    checkScript = 'run check'
}
```

---

🖥 **Environment:**
 - OS: Mac OS X
 - JDK: OpenJDK 1.8 64 bit
 - Gradle: 5.5.1
 - Frontend Gradle plugin: 1.2.1

---

I understand that this probably isn't a bug and is a mistake on my behalf. I would appreciate any help. Thank you!

**Comment by byxor** [comment]
Someone else found a fix for this. Thankfully it's very simple, the properties just need to be set using the `set` method.

```kotlin
frontend {
    nodeVersion.set("6.11.3")
    cleanScript.set("run clean")
    assembleScript.set("run assemble")
    checkScript.set("run check")
}
```

**Comment by vboriesazeau** [comment]
Hi @byxor 
Sorry for the very late answer, and thank you for your feedback.
Configuration introduced in the docs will be provided in Kotlin language in the next release.
Best regards
Vincent

**Comment by vboriesazeau** [comment]
Reopened issue for traceability.
