### ISSUE TITLE
Implement support for incremental builds

### ISSUE THREAD

**Issue by nuth** [Siouan/frontend-gradle-plugin#60]
**Is your feature request related to a problem? Please describe.**
Frontend is built every time.

**Describe the solution you'd like**
To improve build times, it'd be nice to have incremental builds implemented (https://docs.gradle.org/current/userguide/more_about_tasks.html#sec:up_to_date_checks). The inputs and outputs should be known, so no need for extra configuration, although in the case of packinging into a jar, I guess having some option to exclude directories from input/output should be possible.

UPDATE:
Much like my existing issue, I notice this is also something you can do in build.gradle like so:
```
assembleFrontend.inputs.dir projectDir.toString() + "/src" # just for testing
assembleFrontend.outputs.dir projectDir.toString() + "/build"
```
But I think the plugin could provide some appropriate defaults.

**Comment by vboriesazeau** [comment]
Hi @nuth,
Thank you for this feedback.
The plugin is expected to deal with builds incrementally: for instance it shall not download again a Node distribution if the version has not been changed, and the install dir has not been touched.
However, I found some issues some weeks ago, and this behaviour is still buggy. Unfortunately, I don't have time actually to work on a fix.
It's clearly the next thing I would work on in this plugin, I'm aware it can be painful since the plugin is running again tasks whose inputs/outputs have not changed.
BR,
Vincent

**Comment by vboriesazeau** [comment]
Hi @nuth,
I'm starting to deal again with your request, that I may have misunderstood. As exposed some months ago, the plugin relies on Gradle incremental behaviour, when relevant, i.e. when it has control on task's inputs and outputs. This is the case with the `installNode` task and the `installYarn` task. Both tasks are skipped when the configuration has not changed, and distributions have already been downloaded successfully.

With your message, I understand you would like other tasks, e.g. the `assembleFrontend` task, to take benefit from this incremental behaviour. Actually, it does not seem to me possible or desirable. This task itself does not assemble the frontend, like the Gradle `assemble` task that does not assemble anything on its own. It provides the ability to connect the developer's own JS build process to Gradle, and nothing more. Every JS build process is unique to me. This process depends on the project, the language (e.g. TypeScript, Angular, ECMA script version...), the directory layout, etc, chosen by the developer. These choices and the build process are not under the responsibility of the plugin. I mean the plugin is not aware of the inputs and outputs of this build process. It seems to me the incremental feature should be/is already handled by JS precompilers/build tools.

However, if you really want to make one of the plugin task be aware of additional I/O, and take advantage of a custom incremental behaviour, the code you introduced seems to me appropriate.

Actually, I would close this issue soon, unless you want to bring some clarifications. In this case, feel free to continue this discussion.
Thank you for your interest!
BR
Vincent
