### ISSUE TITLE
Control gradle capture log level of tasks through frontend dsl

### ISSUE THREAD

**Issue by nuth** [Siouan/frontend-gradle-plugin#61]
**Is your feature request related to a problem? Please describe.**
Frontend build is creating a lot of noise and should be possible to set in a convenient way.

**Describe the solution you'd like**
At the moment I have a workaround that requires me to set the log level for each task individually like this:
```
installNode.logging.captureStandardOutput LogLevel.DEBUG
installYarn.logging.captureStandardOutput LogLevel.DEBUG
installFrontend.logging.captureStandardOutput LogLevel.DEBUG
assembleFrontend.logging.captureStandardOutput LogLevel.DEBUG
cleanFrontend.logging.captureStandardOutput LogLevel.DEBUG
```
It'd be a lot simpler and readable to do something like:
```
frontend {
  logging.captureStandardOutput LogLevel.DEBUG
}
```

**Comment by vboriesazeau** [comment]
Hi @nuth,
Thank you for this feedback. I understand your need to limit logging. I'll think about a relevant solution as soon as I have some time. I'll try to provide it for the next release.
BR
Vincent
