### ISSUE TITLE
Gradle Publish -> Npm Publish

### ISSUE THREAD

**Issue by napstr** [Siouan/frontend-gradle-plugin#72]
Hi, this plugin so far worked with few surprises for me. Great work!

I've been wondering, what about deploying/publishing artifacts?

I realise not all projects need that functionality, but I do have a few where I would like to tie in the gradle `publish` task and by default execute `npm publish`, with the option just like the other tasks to override the executed command, because I also have a project that uses ng-packagr and puts the output of that into a different directory, so I'd want to be able to create something like 

```
"scripts": {
	...
	...
	"deploy": "cd dist && npm publish"
},
```

in my `package.json` and have something like

```
frontend {
	publishScript = 'run deploy'
}
```

in my `build.gradle`.

Would this be something that fits into the scope of this plugin, or should I rather solve this with some gradle scripting?

Please let me know if you need more information.

**Comment by vboriesazeau** [comment]
Hi @napstr ,
Thank you for your message and your request.
It seems to me an interesting feature.

When you mention the `publish` task, I guess you are talking about the task in the `maven-publish` plugin.

Here are some basic requirements for clarity (may change later if needed):
- The plugin provides a `publishFrontend` task.
- The `publishFrontend` task depends on no task if the `publish` task is not available (e.g. the `maven-publish` plugin is not loaded and applied).
- The `publishFrontend` task depends on the `publish` task if loaded and applied.
- The `publishFrontend` task does nothing if the `publishScript` property is undefined.
- The `publishFrontend` task executes the NPM/Yarn script defined in the new `publishScript` property, if defined.

I may ask you additional questions later, if needed. Thanks again for your help!
Best regards,
Vincent
